### ISSUE TITLE
Download Folder Name Breaks `yarn start`

### ISSUE THREAD

**Issue by hwhelchel** [layerhq/Web-XDK-Messenger#3] opened 2018-02-15 03:46 UTC
When downloading your SDK the folder name was `dashboard%2FLayer-QuickStart-b3dd3e74-abd1-11e7-948a-5b427362218b`.

When running `yarn start` with the web project, the react app wouldn't load. When I moved the web folder out of the folder `dashboard%2FLayer-QuickStart-b3dd3e74-abd1-11e7-948a-5b427362218b` `yarn start` then successfully loaded the react app.

**Comment by nilgradisnik** [comment] 2018-02-15 17:37
That does look strange. That `dashboard%2F` prefix should not be there.  You should have received a zip file `Layer-Quickstart-{UUID}.zip` and the contents of the archive should look like this:
```
android/
ios/
web/
README.md
```
What web browser did you use to download the zip file?

**Comment by hwhelchel** [comment] 2018-02-15 17:40
@nilgradisnik chrome

**Comment by nilgradisnik** [comment] 2018-02-15 18:01
@hwhelchel I am unable to reproduce your issue. That prefix is strange but even with that it should still work. Can expand more on what exactly do you mean "the react app wouldn't load" and if you see any errors in the logs or browser developer console, that would be helpful.

**Comment by M-ZubairAhmed** [comment] 2018-04-03 09:38
could you try `npm` instead. Npm worked for me over Yarn

**Comment by nilgradisnik** [comment] 2018-04-03 21:49
Closing this since we were unable to reproduce.

**Closed by nilgradisnik** 2018-04-03 21:49 UTC
